Fix Python version check.
Before:

    $ python3.6 urlycue --help
    Traceback (most recent call last):
      File "urlycue", line 41, in <module>
        import lib.cli  # pylint: disable=wrong-import-position
      File "<fstring>", line 1
        (await "# Python >= 3.7 is required #")
                                             ^
    SyntaxError: invalid syntax

After:

    $ python3.6 urlycue --help
    urlycue: error: Python >= 3.7 is required