Don't close the event loop on exception.
Closing the loop on exception doesn't seem to fix any real problems.
On the other hand, it causes traceback noise, such as:

    Exception ignored in: <coroutine object process_results at 0xf680cd68>
    Traceback (most recent call last):
      File ".../urlycue/lib/cli.py", line 100, in process_results
      File "/usr/lib/python3.8/asyncio/queues.py", line 165, in get
      File "/usr/lib/python3.8/asyncio/base_events.py", line 719, in call_soon
      File "/usr/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    RuntimeError: Event loop is closed

This reverts commit 9d8e8c8f5c5d0e06eb39e52ba746da19ca98283f.